version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:15.0
    restart: always
    env_file:
      - docker/postgres/.env
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

networks:
   default:
     name: billing_network
