name: Python application

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.8", "3.9"]
    steps:
    - id: checkout
      uses: actions/checkout@v2

    - id: set_up_python
      name: Set up Python ${{matrix.version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.version}}
      continue-on-error: true

    - id: dependencies
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wemake-python-styleguide
        pip install flake8-html
        pip install mypy
        mypy --install-types --non-interactive src/

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      continue-on-error: true

    - id: linter
      name: Lint with styleguide
      if: ${{ always() }}
      run: |
        flake8 . --config=flake8.cfg

        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - id: mypy
      name: Mypy
      if: ${{ always() }}
      run: |
        mypy . --install-types --non-interactive  --config=mypy.cfg --explicit-package-bases --namespace-packages
